### ISSUE TITLE
Mod Name is still Example Mod

### ISSUE THREAD

**Issue by dandin87** [Darkhax-Minecraft/Death-Knell#1]
https://github.com/Darkhax-Minecraft/Death-Knell/blob/1bc098c03a3d3f087dc0eb52434a934bed9f6f4a/Fabric/src/main/resources/fabric.mod.json#L6

**Comment by Darkhax** [comment]
Thanks for the report. Fixed in https://github.com/Darkhax-Minecraft/Death-Knell/commit/f14aae0511dca2232492f05b4e1722ca4fc03246
