### ISSUE TITLE
[BUG] "message.deathknell"

### ISSUE THREAD

**Issue by meowisme** [Darkhax-Minecraft/Death-Knell#14]
### Minecraft Version

1.20.1

### Mod Version

10.0.4

### Mod Loader

Fabric

### What environment are you running the mod in?

Dedicated Server

### Issue Description

I've had multiple situations of death messages showing up like:
![image](https://github.com/Darkhax-Minecraft/Death-Knell/assets/127144330/f46a5f48-17b7-4840-a7ca-7ec636229b77)
Instead of displaying the actual message. I haven't changed anything in the config.

**Comment by Darkhax** [comment]
Hello, this looks like your client doesn't have the localization files installed. Are you sure you installed it on the client, it's required for the mod to work correctly.

**Comment by meowisme** [comment]
I see, I wasn't aware that it was needed client-side as well. Thank you ^^
