### ISSUE TITLE
Cave spider venom death message doesn't work

### ISSUE THREAD

**Issue by kbsmilk** [Darkhax-Minecraft/Death-Knell#2]
I downloaded "DeathKnell-Forge-1.18.2-3.0.1.jar" and discovered that dying to cave spider poison simply displays "%1$s succame to %2Ss venom", no names like other deaths.
Also I wish to point out it should be "succumbed" instead of "succame".

This mod is cool, btw :) I like the Terraria-style messages!

**Comment by Darkhax** [comment]
Thanks for letting me know about this issue, a new update has been pushed that will fix this issue. Glad you enjoyed the mod. 

[Forge Fix](https://www.curseforge.com/minecraft/mc-mods/death-knell/files/3807728)

[Fabric Fix](https://www.curseforge.com/minecraft/mc-mods/death-knell/files/3807727)
