### ISSUE TITLE
ru_ru.json

### ISSUE THREAD

**Issue by Deni-Naka** [Darkhax-Minecraft/Death-Knell#3]
[Pastebin Link](https://pastebin.com/QzMZUDn3)

`{"death.fell.accident.water":"%2$s уснул под водой","message.deathknell.death_by_cookie":"%2$s заставил %1$s съесть слишком много печенек","message.deathknell.death_by_book":"%2$s рассказал %1$s лекцию о смерти","message.deathknell.death_by_axe":"%2$s разрубил %1$s на кусочки","message.deathknell.thwarted":"%2$s толкнул %1$s ","message.deathknell.thwarted.item":"%2$s толкнул %1$s, используя %3$s","message.deathknell.bonked":"%1$s был кокнут %2$s","message.deathknell.bonked.item":"%1$s был кокнут %2$s, использующим%3$s","message.deathknell.defeated":"%1$s проиграл %2$s","message.deathknell.defeated.item":"%1$s проиграл %2$s, использующим%3$s","message.deathknell.butchered":"%1$s был разрублен %2$s","message.deathknell.butchered.item":"%1$s был разрублен %2$s, использующим%3$s","message.deathknell.assassinate":"%1$s был заказан %2$s","message.deathknell.assassinate.item":"%1$s был заказан %2$s и убит с помощью%3$s","message.deathknell.eliminated":"%1$s был кокнут%2$s","message.deathknell.eliminated.item":"%1$s был кокнул %2$s, использующим%3$s","message.deathknell.extinguished":"Жизнь %1$s оборвалась из-за %2$s","message.deathknell.extinguished.item":"Жизнь %1$s оборвалась из-за %2$s, использующим%3$s","message.deathknell.terminated":"%1$s был разгромлен%2$s","message.deathknell.terminated.item":"%1$s был разгромлен %2$s, использующим%3$s","message.deathknell.done_in":"%1$s улетел в космос %2$s","message.deathknell.done_in.item":"%1$s улетел в космос %2$s благодаря%3$s","message.deathknell.executed":"%1$s был казнён %2$s","message.deathknell.executed.item":"%1$s был казнён %2$s","message.deathknell.stopped":"%2$s остановил %1$s","message.deathknell.stopped.item":"%2$s остановил %1$s благодаря %3$s","message.deathknell.stifle":"%1$s был подавлен %2$s","message.deathknell.stifle.item":"%1$s was подавлен by %2$s использующим%3$s","message.deathknell.slaughter":"%1$s был раздавлен %2$s","message.deathknell.slaughter.item":"%1$s был раздавлен %2$s использующим%3$s","message.deathknell.exterminated":"%1$s был испепелён %2$s","message.deathknell.exterminated.item":"%1$s был испепелён благодаря %2$s , ипользущим%3$s","message.deathknell.vanquished":"%1$s был побежден %2$s","message.deathknell.vanquished.item":"%1$s проиграл %2$s","message.deathknell.bested":"%1$s был повержен %2$s","message.deathknell.bested.item":"%1$s проиграл %2$s ипользующего %3$s","message.deathknell.trounced":"%1$s был побежден%2$s","message.deathknell.trounced.item":"%1$s был побежден %2$s используя%3$s","message.deathknell.down_with_ship":"%1$s пошёл на дно с кораблём","message.deathknell.incinerated":"%2$s сжёг %1$s","message.deathknell.reduce_to_ash":"%2$s прекратил %1$s в пепел","message.deathknell.cooked_alive":"%1$s был сожженой заживо%2$s","message.deathknell.spider_venom":"%1$s поддался яду %2$s venom","message.deathknell.dissolve":"%2$s разрушил %1$s","message.deathknell.slime_food":"%1$s стал кормом для %2$s","message.deathknell.respect_habitat":"%1$s не уважал очаг %2$s","message.deathknell.disturb_den":"%1$s разболтал секреты %2$s ","message.deathknell.watery_grave":"%2$s отправил %1$s в водную могилу","message.deathknell.stared_down":"%1$s посмотрев в глаза %2$1","message.deathknell.fall_bounce":"%1$s забыл подпрыгнуть","message.deathknell.fall_gravity":"%1$s был убит Гравитацией","message.deathknell.fall_parachute":"%1$s забыл парашют","message.deathknell.drown_breath":"%1$s забыл задержать дыхание","message.deathknell.drown_fishes":"%1$s спит вместе с рыбами","message.deathknell.drown_fish_food":"%1$s решил стать кормом для рыб"}`

**Comment by Darkhax** [comment]
Russian support was included in https://github.com/Darkhax-Minecraft/Death-Knell/commit/c569d12451e6002cb34b5a86aebaceb61ba70e49

**Comment by Deni-Naka** [comment]
but there is no ru_ru lang

**Comment by Darkhax** [comment]
Oh interesting, it looks like the file got lost when porting to 1.19.1. I will correct this.
