### ISSUE TITLE
zh_cn.json

### ISSUE THREAD

**Issue by Syn7hCha1n3aw** [Darkhax-Minecraft/Death-Knell#5]
{"death.fell.accident.water":"%2$s 不慎溺水","message.deathknell.death_by_cookie":"%2$s 向 %1$s 嘴里塞了太多曲奇","message.deathknell.death_by_book":"%2$s 让 %1$s 感受到了知识的力量","message.deathknell.death_by_axe":"%2$s 将 %1$s 砍成肉块","message.deathknell.thwarted":"%1$s 打成肉酱了 %2$s","message.deathknell.thwarted.item":"%1$s 被 %2$s 用 %3$s 打成肉酱了","message.deathknell.bonked":"%1$s 被 %2$s 创死了","message.deathknell.bonked.item":"%1$s 被 %2$s 用 %3$s 创死了","message.deathknell.defeated":"%1$s 被 %2$s 击败了","message.deathknell.defeated.item":"%1$s 被 %2$s 用 %3$s 击败了","message.deathknell.butchered":"%1$s 遭到了 %2$s 惨无人寰的屠杀","message.deathknell.butchered.item":"%1$s 被 %2$s 用 %3$s 杀害","message.deathknell.assassinate":"%1$s 被 %2$s 刺杀了","message.deathknell.assassinate.item":"%1$s 被 %2$s 用 %3$s 刺杀了","message.deathknell.eliminated":"%1$s 被 %2$s 淘汰下场","message.deathknell.eliminated.item":"%1$s 被 %2$s 和他的 %3$s 淘汰下场","message.deathknell.extinguished":"%2$s 结束了 %1$s 悲惨的一生","message.deathknell.extinguished.item":"%2$s 用 %3$s 结束了 %1$s 悲惨的一生","message.deathknell.terminated":"%1$s 被 %2$s 终结了","message.deathknell.terminated.item":"%1$s 被 %2$s 用 %3$s 终结了","message.deathknell.done_in":"%1$s 被 %2$s 揍垮了","message.deathknell.done_in.item":"%1$s 被 %2$s 用 %3$s 揍垮了","message.deathknell.executed":"%2$s 为 %1$s 执行了死刑","message.deathknell.executed.item":"%2$s 为 %1$s 执行了死刑","message.deathknell.stopped":"%2$s 为 %1$s 的生命画上了休止符","message.deathknell.stopped.item":"%2$s 用 %3$s 为 %1$s 的生命画上了休止符","message.deathknell.stifle":"%2$s 扼杀了 %1$s","message.deathknell.stifle.item":"%2$s 用 %3$s 扼杀了 %1$s","message.deathknell.slaughter":"%2$s 宰了 %1$s","message.deathknell.slaughter.item":"%2$s 用 %3$s 把 %1$s 宰了","message.deathknell.exterminated":"%2$s 消灭了 %1$s","message.deathknell.exterminated.item":"%1$s 被 %2$s 用 %3$s 消灭了","message.deathknell.vanquished":"%2$s 击败了他的对手 %1$s","message.deathknell.vanquished.item":"%2$s's 用 %3$s 击败了他的对手 %1$s","message.deathknell.bested":"%1$s 被 %2$s 做掉了","message.deathknell.bested.item":"%1$s 被 %2$s 用 %3$s 做掉了","message.deathknell.trounced":"%1$s 让 %2$s 再起不能","message.deathknell.trounced.item":"%2$s 用 %3$s 让 %1$s 再起不能","message.deathknell.down_with_ship":"%1$s 随船沉入大洋深处","message.deathknell.incinerated":"%1$s 被 %2$s 推进了焚化炉","message.deathknell.reduce_to_ash":"%1$s 化为灰烬","message.deathknell.cooked_alive":"%1$s 被 %2$s 做成了生姜烧肉","message.deathknell.spider_venom":"%1$s 被 %2$s 毒杀","message.deathknell.dissolve":"%1$s 被 %2$s 溶解了","message.deathknell.slime_food":"%1$s 成了 %2$s 的盘中餐","message.deathknell.respect_habitat":"%1$s 对 %2$s 的栖息地不敬","message.deathknell.disturb_den":"%1$s 生前不慎踏入了 %2$s 的巢穴","message.deathknell.watery_grave":"%2$s 将 %1$s 拖入水中","message.deathknell.stared_down":"%1$s 受到了 %2$1 的死亡凝视","message.deathknell.fall_bounce":"%1$s 下辈子应该会记得自己脚上没长粘液块","message.deathknell.fall_gravity":"看来 %1$s 与牛顿不熟","message.deathknell.fall_parachute":"%1$s 忘记带水桶了","message.deathknell.drown_breath":"%1$s 无法呼吸","message.deathknell.drown_fishes":"%1$s 与鱼同眠","message.deathknell.drown_fish_food":"%1$s 成鱼饲料了"}

**Comment by Darkhax** [comment]
Thanks for helping translate the mod. Could you please submit this as a GitHub Pull Request?

**Comment by Syn7hCha1n3aw** [comment]
already submit :)
very good mod btw
